[package]
name = "cld3"
version = "0.1.0"
edition = "2021"
links = "cxx-cld3"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
glob = "0.3"